<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Core\Module'                        => __DIR__ . '/Module.php',
    'Core\Controller\UserController'     => __DIR__ . '/src/Core/Controller/UserController.php',
    'CoreTest\Framework\TestCase'        => __DIR__ . '/tests/CoreTest/Framework/TestCase.php',
    'CoreTest\SampleTest'                => __DIR__ . '/tests/CoreTest/SampleTest.php',
);